from ambulance_emergency_response.agents.random_agent import RandomAgent
from ambulance_emergency_response.agents.greedy_agent import GreedyAgent
from ambulance_emergency_response.agents.social_convetion_agent import ConventionAgent